const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const userSchema = new Schema({
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true,
  },
  password: {
    type: String,
    required: true,
  },
  fullName: {
    type: String,
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  role: { 
    type: String, 
    enum: ['owner', 'staff', 'superadmin'], 
    default: 'owner' 
  },
  parentOwnerId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    default: null // Staff ke case me yahan owner ki ID hogi
  },
  isPremium: { type: Boolean, default: false },
  walletBalance: { type: Number, default: 0 },
  totalAiCost: { type: Number, default: 0 },
  aiCredits: { type: Number, default: 100 }, // Starting with 100 Free AI Replies
  referralCode: { type: String, unique: true, sparse: true }, // E.g., 'SCALIO-AB12'
  referredBy: { type: String }, // Code of the user who referred them
  discountAvailable: { type: Boolean, default: false }, // 20% off on next billing
  apiKey: { type: String, unique: true, sparse: true },
  websiteUrl: { type: String },
  ownerPhone: { type: String }, // Shop owner's personal WhatsApp number
  isOwnerPhoneVerified: { type: Boolean, default: false },
  connectedPlatforms: [{ 
    platformName: { type: String }, // e.g. newpropertyhub, vyaparindia
    profileUrl: { type: String },
    isActive: { type: Boolean, default: true }
  }],
  staff: [{
    name: { type: String },
    phone: { type: String },
    email: { type: String }, // Staff login email
    password: { type: String }, // Hashed password for staff login
    role: { type: String, enum: ['sales', 'support', 'manager'] }, // Multi-staff routing
  }],
  // New Fields for Local Market Lead Distribution
  businessModel: { type: String, enum: ['online', 'offline', 'both'], default: 'online' },
  servedPinCodes: [{ type: String }], // Array of local pin codes they deliver to
  productCategories: [{ type: String }], // e.g. ["Electronics", "Mobiles"]
  vyaparWebsiteUrl: { type: String }, // Link to their vyaparindia.online page
  optInForSharedLeads: { type: Boolean, default: true }, // Willing to buy cancelled leads from others
  businessProfile: {
    description: { type: String },
    divisions: [{ 
      name: { type: String }, 
      description: { type: String } // E.g., "Real Estate", "Electronics" for Cross-Selling
    }],
    catalog: [{
      itemName: { type: String },
      brand: { type: String },
      price: { type: Number },
      description: { type: String },
      imageUrl: { type: String }
    }],
    faqs: { type: Map, of: String }, // Auto-generated by AI
    rules: [{ type: String }]
  },
  savedMedia: [{
    mediaId: { type: String },
    caption: { type: String },
    timestamp: { type: Date, default: Date.now }
  }],
  whatsappConfig: {
    accessToken: { type: String },
    phoneNumberId: { type: String },
    webhookVerifyToken: { type: String },
    wabaId: { type: String } // Required by Meta for Template Approvals
  },
  autoReplies: [{
    triggerWord: { type: String },
    replyMessage: { type: String }
  }],
  trainingData: [{
    question: { type: String, required: true },
    status: { type: String, enum: ['unanswered', 'answered'], default: 'unanswered' },
    customerPhone: { type: String },
    createdAt: { type: Date, default: Date.now }
  }],
  messageStats: {
    sent: { type: Number, default: 0 },
    delivered: { type: Number, default: 0 },
    read: { type: Number, default: 0 }
  }
  // You might want to add roles, profile pictures, etc.
});

const User = mongoose.model('User', userSchema);

module.exports = User;
