const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const Schema = mongoose.Schema;

// ✅ NEW: Comprehensive schema for Instagram Business connections.
// This will store all the new data from the updated login flow.
const instagramConfigSchema = new Schema({
  // Core IDs
  instagramUserId: { type: String }, // The user who authorized the app
  instagramBusinessAccountId: { type:String },
  facebookPageId: { type: String },
  businessId: { type: String }, // Meta Business Manager ID
  
  // Authentication & Permissions
  accessToken: { type: String },
  tokenType: { type: String, default: 'bearer' },
  tokenExpiresAt: { type: Date }, // ✅ FIX: Renamed 'expiresAt' to 'tokenExpiresAt' to match the object being saved in authController.js. This was the critical bug preventing the token expiry from being saved.
  grantedPermissions: [{ type: String }],

  // Metadata
  username: { type: String },
  profilePictureUrl: { type: String },
  lastVerifiedAt: { type: Date },
}, { _id: false });

const userSchema = new Schema({
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true,
  },
  password: {
    type: String,
    required: true,
  },
  supabaseId: {
    type: String,
    unique: true,
    sparse: true,
  },
  fullName: {
    type: String,
    required: true,
  },
  brandKit: {
    logoUrl: { type: String },
    businessName: { type: String },
    phone: { type: String },
    email: { type: String },
    website: { type: String },
    primaryColor: { type: String, default: '#000000' },
    secondaryColor: { type: String, default: '#FFFFFF' },
    font: { type: String, default: 'Arial' },
    instagram: { type: String },
    facebook: { type: String },
    whatsapp: { type: String },
    address: { type: String },
    products: [{ type: String }],
    category: { type: String },
    defaultCta: { type: String, default: 'Learn More' },
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  role: { 
    type: String, 
    enum: ['owner', 'staff', 'superadmin', 'tester'], 
    default: 'owner' 
  },
  parentOwnerId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    default: null // Staff ke case me yahan owner ki ID hogi
  },
  isPremium: { type: Boolean, default: false },
  walletBalance: { type: Number, default: 0 },
  totalAiCost: { type: Number, default: 0 },
  aiCredits: { type: Number, default: 100 }, // Starting with 100 Free AI Replies
  referralCode: { type: String, unique: true, sparse: true }, // E.g., 'SCALIO-AB12'
  referredBy: { type: String }, // Code of the user who referred them
  discountAvailable: { type: Boolean, default: false }, // 20% off on next billing
  apiKey: { type: String, unique: true, sparse: true },
  websiteUrl: { type: String },
  ownerPhone: { type: String }, // Shop owner's personal WhatsApp number
  isOwnerPhoneVerified: { type: Boolean, default: false },
  connectedPlatforms: [{ 
    platformName: { type: String }, // e.g. newpropertyhub, vyaparindia
    profileUrl: { type: String },
    isActive: { type: Boolean, default: true }
  }],
  staff: [{
    name: { type: String },
    phone: { type: String },
    email: { type: String }, // Staff login email
    password: { type: String }, // Hashed password for staff login
    role: { type: String, enum: ['sales', 'support', 'manager'] }, // Multi-staff routing
  }],
  // New Fields for Local Market Lead Distribution
  businessModel: { type: String, enum: ['online', 'offline', 'both'], default: 'online' },
  servedPinCodes: [{ type: String }], // Array of local pin codes they deliver to
  productCategories: [{ type: String }], // e.g. ["Electronics", "Mobiles"]
  vyaparWebsiteUrl: { type: String }, // Link to their vyaparindia.online page
  optInForSharedLeads: { type: Boolean, default: true }, // Willing to buy cancelled leads from others
  businessProfile: {
    catalog: [{
      itemName: { type: String },
      brand: { type: String },
      price: { type: Number },
      description: { type: String },
      imageUrl: { type: String }
    }],
    faqs: { type: Map, of: String }, // Auto-generated by AI
  },
  workspaces: [{ 
    name: { type: String }, 
    description: { type: String }, // E.g., "Real Estate", "Electronics" for Cross-Selling
    email: { type: String }, // Branch Email ID
    // --- Separate Connections for each Workspace ---
    whatsappConfig: {
      accessToken: { type: String },
      phoneNumberId: { type: String },
      wabaId: { type: String }
    },
    instagramConfig: instagramConfigSchema, // ✅ USE: Using the new comprehensive schema
    // --- Separate AI Brain for each Workspace ---
    businessDescription: { type: String, default: '' }, // AI Training Data
    aiRules: { type: String, default: '' }, // Custom rules for AI
    aiAgentEnabled: { type: Boolean, default: false },
    commentAiReplyEnabled: { type: Boolean, default: false },
    commentAiPostSettings: [{
      postId: { type: String },
      commentAiReplyEnabled: { type: Boolean, default: true }
    }],
    postAutomations: [{
      postId: { type: String },
      thumbnailUrl: { type: String },
      triggerWord: { type: String },
      replyMessage: { type: String },
      publicReply: { type: String },
      fileUrl: { type: String },
      deliveryMode: { type: String, enum: ['direct', 'button', 'instant_shortcut', 'hybrid'], default: 'direct' },
      commentAiReplyEnabled: { type: Boolean, default: false },
      stats: {
        sentCount: { type: Number, default: 0 },
        clickedCount: { type: Number, default: 0 }
      }
    }],
    // --- Social links for each specific workspace ---
    instagram: { type: String },
    facebook: { type: String },
    website: { type: String }
  }],
  savedMedia: [{
    mediaId: { type: String },
    caption: { type: String },
    timestamp: { type: Date, default: Date.now }
  }],
  whatsappConfig: {
    accessToken: { type: String },
    phoneNumberId: { type: String },
    webhookVerifyToken: { type: String },
    wabaId: { type: String } // Required by Meta for Template Approvals
  },
  instagramConfig: instagramConfigSchema, // ✅ USE: Using the new comprehensive schema
  // Server-side, 10-minute state for the account picker. It is never sent in profile responses.
  pendingInstagramConnection: {
    workspaceId: { type: String },
    accessToken: { type: String },
    tokenExpiresAt: { type: Date },
    expiresAt: { type: Date },
    accounts: [{
      accountId: { type: String },
      pageId: { type: String },
      pageName: { type: String },
      pageToken: { type: String }
    }]
  },
  // --- New AI-related fields ---
  businessName: { type: String, default: '' },
  businessDescription: { type: String, default: '' }, // AI Training Data
  aiRules: { type: String, default: '' }, // Custom rules for AI
  fallbackAction: { type: String, enum: ['notify_owner', 'wait_for_human'], default: 'notify_owner' }, // AI fallback
  aiAgentEnabled: { type: Boolean, default: true }, // Master switch for AI
  commentAiReplyEnabled: { type: Boolean, default: false },
  commentAiPostSettings: [{
    postId: { type: String },
    commentAiReplyEnabled: { type: Boolean, default: true }
  }],
  autoReplies: [{
    triggerWord: { type: String },
    replyMessage: { type: String }
  }],
  postAutomations: [{
    postId: { type: String }, // Instagram media ID
    thumbnailUrl: { type: String }, // To display in UI
    triggerWord: { type: String },
    replyMessage: { type: String },
    publicReply: { type: String },
    fileUrl: { type: String }, // Cloudinary PDF/Image link
    deliveryMode: { type: String, enum: ['direct', 'button', 'instant_shortcut', 'hybrid'], default: 'direct' },
    stats: {
      sentCount: { type: Number, default: 0 },
      clickedCount: { type: Number, default: 0 }
    }
  }],
  trainingData: [{
    question: { type: String, required: true },
    status: { type: String, enum: ['unanswered', 'answered'], default: 'unanswered' },
    customerPhone: { type: String },
    createdAt: { type: Date, default: Date.now }
  }],
  messageStats: {
    sent: { type: Number, default: 0 },
    delivered: { type: Number, default: 0 },
    read: { type: Number, default: 0 }
  },
  // --- Cloud Storage & Backup Integrations ---
  googleSheetsConfig: {
    // 🚀 DEPRECATED: This will be merged into the new `googleConfig` object.
    // This is kept temporarily for backward compatibility during migration.
    accessToken: { type: String },
    refreshToken: { type: String },
    spreadsheetId: { type: String },
    connectedEmail: { type: String },
    // 🚀 NEW: Centralized Google Config for Sheets, Drive, etc.
    backupFolderId: { type: String }, // ID of the 'DealClose AI Backups' folder in user's Drive
    lastBackupAt: { type: Date }
  },
});

userSchema.pre('save', async function () {
  // 🚀 PERMANENT FIX: This is the most critical guard.
  // It ensures that the password hashing logic ONLY runs if the password field
  // was actually modified in this 'save' operation. This prevents accidental
  // re-hashing of an already-hashed password when other fields (like 'role') are updated.
  if (!this.isModified('password')) {
    return;
  }

  // Hash the new password before saving. Any error is rejected from this async
  // middleware and Mongoose propagates it to the save operation.
  this.password = await bcrypt.hash(this.password, 10);
});

const User = mongoose.model('User', userSchema);

module.exports = User;
