const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const userSchema = new Schema({
  email: {
    type: String,
    required: true,
    unique: true,
    trim: true,
    lowercase: true,
  },
  password: {
    type: String,
    required: true,
  },
  fullName: {
    type: String,
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  role: { 
    type: String, 
    enum: ['owner', 'staff', 'superadmin'], 
    default: 'owner' 
  },
  parentOwnerId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    default: null // Staff ke case me yahan owner ki ID hogi
  },
  isPremium: { type: Boolean, default: false },
  walletBalance: { type: Number, default: 0 },
  totalAiCost: { type: Number, default: 0 },
  aiCredits: { type: Number, default: 100 }, // Starting with 100 Free AI Replies
  referralCode: { type: String, unique: true, sparse: true }, // E.g., 'SCALIO-AB12'
  referredBy: { type: String }, // Code of the user who referred them
  discountAvailable: { type: Boolean, default: false }, // 20% off on next billing
  apiKey: { type: String, unique: true, sparse: true },
  websiteUrl: { type: String },
  ownerPhone: { type: String }, // Shop owner's personal WhatsApp number
  isOwnerPhoneVerified: { type: Boolean, default: false },
  connectedPlatforms: [{ 
    platformName: { type: String }, // e.g. newpropertyhub, vyaparindia
    profileUrl: { type: String },
    isActive: { type: Boolean, default: true }
  }],
  staff: [{
    name: { type: String },
    phone: { type: String },
    email: { type: String }, // Staff login email
    password: { type: String }, // Hashed password for staff login
    role: { type: String, enum: ['sales', 'support', 'manager'] }, // Multi-staff routing
  }],
  // New Fields for Local Market Lead Distribution
  businessModel: { type: String, enum: ['online', 'offline', 'both'], default: 'online' },
  servedPinCodes: [{ type: String }], // Array of local pin codes they deliver to
  productCategories: [{ type: String }], // e.g. ["Electronics", "Mobiles"]
  vyaparWebsiteUrl: { type: String }, // Link to their vyaparindia.online page
  optInForSharedLeads: { type: Boolean, default: true }, // Willing to buy cancelled leads from others
  businessProfile: {
    catalog: [{
      itemName: { type: String },
      brand: { type: String },
      price: { type: Number },
      description: { type: String },
      imageUrl: { type: String }
    }],
    faqs: { type: Map, of: String }, // Auto-generated by AI
  },
  workspaces: [{ 
    name: { type: String }, 
    description: { type: String }, // E.g., "Real Estate", "Electronics" for Cross-Selling
    email: { type: String }, // Branch Email ID
    // --- Separate Connections for each Workspace ---
    whatsappConfig: {
      accessToken: { type: String },
      phoneNumberId: { type: String },
      wabaId: { type: String }
    },
    // Canonical Instagram connection for a workspace.
    instagramConfig: {
      accessToken: { type: String },
      instagramAccountId: { type: String },
      facebookPageId: { type: String },
      tokenExpiresAt: { type: Date }
    },
    // --- Separate AI Brain for each Workspace ---
    businessDescription: { type: String, default: '' }, // AI Training Data
    aiRules: { type: String, default: '' }, // Custom rules for AI
    // --- Social links for each specific workspace ---
    instagram: { type: String },
    facebook: { type: String },
    website: { type: String }
  }],
  savedMedia: [{
    mediaId: { type: String },
    caption: { type: String },
    timestamp: { type: Date, default: Date.now }
  }],
  whatsappConfig: {
    accessToken: { type: String },
    phoneNumberId: { type: String },
    webhookVerifyToken: { type: String },
    wabaId: { type: String } // Required by Meta for Template Approvals
  },
  instagramConfig: {
    accessToken: { type: String }, // Page Access Token (igAccessToken)
    instagramAccountId: { type: String }, // Instagram Business/Creator ID
    facebookPageId: { type: String }, // Linked FB Page ID
    tokenExpiresAt: { type: Date }
  },
  // Server-side, 10-minute state for the account picker. It is never sent in profile responses.
  pendingInstagramConnection: {
    workspaceId: { type: String },
    accessToken: { type: String },
    tokenExpiresAt: { type: Date },
    expiresAt: { type: Date },
    accounts: [{
      accountId: { type: String },
      pageId: { type: String },
      pageName: { type: String },
      pageToken: { type: String }
    }]
  },
  // --- New AI-related fields ---
  businessName: { type: String, default: '' },
  businessDescription: { type: String, default: '' }, // AI Training Data
  aiRules: { type: String, default: '' }, // Custom rules for AI
  fallbackAction: { type: String, enum: ['notify_owner', 'wait_for_human'], default: 'notify_owner' }, // AI fallback
  aiAgentEnabled: { type: Boolean, default: true }, // Master switch for AI
  autoReplies: [{
    triggerWord: { type: String },
    replyMessage: { type: String }
  }],
  postAutomations: [{
    postId: { type: String }, // Instagram media ID
    thumbnailUrl: { type: String }, // To display in UI
    triggerWord: { type: String },
    replyMessage: { type: String },
    fileUrl: { type: String }, // Cloudinary PDF/Image link
    deliveryMode: { type: String, enum: ['direct', 'button'], default: 'button' },
    stats: {
      sentCount: { type: Number, default: 0 },
      clickedCount: { type: Number, default: 0 }
    }
  }],
  trainingData: [{
    question: { type: String, required: true },
    status: { type: String, enum: ['unanswered', 'answered'], default: 'unanswered' },
    customerPhone: { type: String },
    createdAt: { type: Date, default: Date.now }
  }],
  messageStats: {
    sent: { type: Number, default: 0 },
    delivered: { type: Number, default: 0 },
    read: { type: Number, default: 0 }
  },
  // --- Cloud Storage & Backup Integrations ---
  googleSheetsConfig: {
    accessToken: { type: String },
    refreshToken: { type: String },
    spreadsheetId: { type: String } // User ki Google Sheet ka ID jahan data jayega
  }
  // You might want to add roles, profile pictures, etc.
});

const User = mongoose.model('User', userSchema);

module.exports = User;
